/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.byui.teamawesome.sudoku260.frames;

import edu.byui.teamawesome.sudoku260.Board;
import edu.byui.teamawesome.sudoku260.Board.Cell;
import edu.byui.teamawesome.sudoku260.uicomponents.TextCell;
import edu.byui.teamawesome.sudoku260.values.AlphaValues;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author ken
 */
public class GameFrame extends javax.swing.JFrame {

    private Board board;
    private ArrayList<TextCell> cellList = new ArrayList<TextCell>();
    
    private JLabel possibleValuesLabel;
    /**
     * Creates new form GameFrame
     */
    public GameFrame(Board board) {
        this.board = board;
        
        this.setLayout(new FlowLayout(FlowLayout.LEADING, 0, 0));
        this.setSize(400, 280);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        
        jBoardFrame = new javax.swing.JPanel();
        jBoardFrame.setLayout(new GridLayout(0, 9));
        
        
        ChangeListener listener = new ChangeListener();
        CellFocusHandler focusHandler = new CellFocusHandler();
        //New Text Field Test:
        for(Cell cell : board.getBoard()) {
            TextCell aCell = new TextCell(cell);
            jBoardFrame.add(aCell);
            cellList.add(aCell);
            aCell.setChangeListener(listener);
            aCell.addFocusListener(focusHandler);
        }
        this.add(jBoardFrame);
                
        JPanel jMenuFrame = new javax.swing.JPanel();
        jMenuFrame.setLayout(new GridLayout(0, 1));
        
        ButtonGroup translatorGroup = new ButtonGroup();
        TranslatorHandler translatorHandler = new TranslatorHandler();
        JRadioButton byuiButton = new JRadioButton("BYU-Idaho");
        byuiButton.setActionCommand(Board.ValueTranslators.ALPHA.toString());
        byuiButton.setSelected(true);
        byuiButton.addActionListener(translatorHandler);
        
        JRadioButton numButton = new JRadioButton("Numeric");
        numButton.setActionCommand(Board.ValueTranslators.NUMERIC.toString());
        numButton.addActionListener(translatorHandler);
        
        
        translatorGroup.add(byuiButton);
        translatorGroup.add(numButton);
        
        jMenuFrame.add(byuiButton);
        jMenuFrame.add(numButton);
        
        possibleValuesLabel = new JLabel("");
        jMenuFrame.add(possibleValuesLabel);
        this.add(jMenuFrame); 
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    private void refresh() {
        for(TextCell cell : cellList) {
            cell.refresh();
        }
    }
    
    private void retranslate() {
        for(TextCell cell : cellList) {
            cell.retranslate();
        }
    }
    
    private class ChangeListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            refresh();
        }
        
    }
    
    
    private class TranslatorHandler implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Board.setValueTranslator(e.getActionCommand());
            retranslate();
        }
        
    }
    
    private class CellFocusHandler implements FocusListener {

        @Override
        public void focusGained(FocusEvent e) {
            TextCell thisElement = (TextCell)e.getComponent();
            ArrayList<Integer> possibleValues = thisElement.getPossibleValues();
            String posValues = "Possible Values: ";
            for(Integer val : possibleValues) {
                posValues += Board.valueTranslator.getValueAtOrdinal(val - 1) + " ";
            }
            possibleValuesLabel.setText(posValues);
        }

        @Override
        public void focusLost(FocusEvent e) {
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jBoardFrame = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku");

        jBoardFrame.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jBoardFrameLayout = new javax.swing.GroupLayout(jBoardFrame);
        jBoardFrame.setLayout(jBoardFrameLayout);
        jBoardFrameLayout.setHorizontalGroup(
            jBoardFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        jBoardFrameLayout.setVerticalGroup(
            jBoardFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBoardFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBoardFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jBoardFrame;
    // End of variables declaration//GEN-END:variables
}
