/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.byui.teamawesome.sudoku260.frames;

import edu.byui.teamawesome.sudoku260.Board;
import edu.byui.teamawesome.sudoku260.Board.Cell;
import edu.byui.teamawesome.sudoku260.uicomponents.TextCell;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Label;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ken
 */
public class GameFrame extends javax.swing.JFrame {

    private Board board;
    
    /**
     * Creates new form GameFrame
     */
    public GameFrame(Board board) {
        this.board = board;
        
        this.setLayout(new FlowLayout(FlowLayout.LEADING, 0, 0));
        this.setSize(400, 280);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        
        jBoardFrame = new javax.swing.JPanel();
        jBoardFrame.setLayout(new GridLayout(0, 9));
        
        
        //New Text Field Test:
        for(Cell cell : board.getBoard()) {
            TextCell aCell = new TextCell(cell);
            jBoardFrame.add(aCell);
        }
        this.add(jBoardFrame);
                
        
        JPanel jMenuFrame = new javax.swing.JPanel();
        this.add(jMenuFrame);
//        initComponents();
//        jBoardFrame.add(new JTextField("A Test"));
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBoardFrame = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku");

        jBoardFrame.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jBoardFrameLayout = new javax.swing.GroupLayout(jBoardFrame);
        jBoardFrame.setLayout(jBoardFrameLayout);
        jBoardFrameLayout.setHorizontalGroup(
            jBoardFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        jBoardFrameLayout.setVerticalGroup(
            jBoardFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBoardFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBoardFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBoardFrame;
    // End of variables declaration//GEN-END:variables
}
